routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('test', 'JasperController@test');

Route::get('check', 'CheckController@index');
Route::get('send/email', 'MailController@sendemail');

Route::get('/register_view', 'Auth\RegisterController@register_view');
Auth::routes();
Auth::routes(['verify' => true]);

//For All Logged in Users
Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    Route::resource('settings', 'SettingController')->only(['index', 'store']);
    Route::resource('saleagent', 'SaleAgentController');
    Route::resource('admin', 'AdminController');
    Route::resource('client', 'ClientController');
    Route::get('edit-account', 'UserController@edit_account')->name('edit-account');
    Route::put('update-account', 'UserController@update_account')->name('update-account');
    Route::get('user/{id}/profile', 'UserController@show_profile')->name('profile.show');
    Route::get('accont/{id}', 'Homecontroller@account_detial')->name('account.show');
    Route::prefix('client')->group(function () {
        Route::get('get-usage/{id}', 'ClientController@get_usage');
    });


    Route::resource('devices', 'DeviceController');
    Route::resource('connections', 'ConnectionController');

    Route::prefix('connections')->group(function () {
        Route::get('{id}/add-deal-info', 'ConnectionController@deal_info')->name('connection.deal_info');
    });
    Route::get('device-connections/{slug}', 'DeviceController@connections')->name('device.connections');
    Route::put('add-connection/{id}', 'DeviceController@store_connection')->name('connection.store');
    Route::put('remove-connection/{id}', 'DeviceController@remove_connection')->name('connection.remove');


    Route::resource('packages', 'PackageController')->except(['show', 'destroy']);


//Admin only routes
    Route::group(['middleware' => ['role:admin|superuser', 'auth']], function () {
        Route::get('sync-devices', 'DeviceController@sync_devices')->name('sync');
        Route::get('sync-devices-ajax', 'DeviceController@sync_devices_ajax')->name('sync-ajax');

        Route::get('quote/{quote_id}/attach_connection', 'DealController@attach_connections')->name('attach.deal_conn');
        Route::post('quote/{quote_id}/attach_connection', 'DealController@store_attach_connections')->name('store.deal_conn');

        Route::get('bulk-deal-info/create', 'ConnectionController@deal_info_bulk')->name('deal_info_bulk');
        Route::get('ajax/client_deals/{client_id}', 'ConnectionController@client_deals');
        Route::put('add-bulk-deal-info', 'ConnectionController@store_deal_info_bulk')->name('store_deal_info');

        Route::get('admin-notifications', 'NotificationController@admin')->name('admin.notifications')->middleware('ajax');
        Route::get('admin-notification-read/{id}', 'NotificationController@admin_read')->middleware('ajax');
        Route::get('admin-notification-readall', 'NotificationController@admin_readall')->name('admin.readall')->middleware('ajax');
        Route::get('assign/sims', 'AssignSimController@create')->name('assign.sim.create');
        Route::post('assign/sims', 'AssignSimController@store')->name('assign.sim.store');
        Route::get('assign/sims/{id}/edit', 'AssignSimController@edit')->name('assign.sim.edit');
        Route::post('assign/sims/{id}/update', 'AssignSimController@update')->name('assign.sim.update');
        Route::get('assign/list', 'AssignSimController@index')->name('assign.sim.index');
        Route::get('deassign/{id}/sim', 'AssignSimController@deassign')->name('deassign.sim');
    });



    Route::get('connection-dayssearch/{iccid}/{start}/{end}', 'ConnectionController@days_search')->name('connection.daysearch');
    Route::get('connection-monthsearch/{iccid}/{start}/{end}', 'ConnectionController@month_search')->name('connection.monthsearch');


    Route::resource('quote', 'QuoteController');
    Route::prefix('quote/{quote_id}')->group(function () {
        Route::resource('deal', 'DealController');
        Route::get('/deal/individual/create', 'DealController@create')->name('deal.individual');

        Route::prefix('/deal/pooled')->group(function () {
            Route::get('/create', 'DealController@pooled')->name('deal.pooled');
            Route::post('/store', 'DealController@store_pooled')->name('store.pooled');
        });

        Route::get('send', 'QuoteController@send')->name('quote.send');
        Route::put('save', 'QuoteController@save_paymentplan')->name('save.paymentplan');
        Route::get('approve/', 'QuoteController@approve')->name('quote.approve');
    });
    Route::get('get-quote-price/{deal_type}/{product_type_id}/{data_usage}', 'QuoteController@get_quote_price');
    Route::get('get-volume/{deal_type}/{volume_id}', 'QuoteController@get_volume');
    Route::get('get-data-volume/{deal_type}/{type}', 'QuoteController@get_datavolume');

    Route::resource('wallet', 'WalletController')->except(['show', 'delete']);

    //Notifications
    Route::get('saleagent-notifications', 'NotificationController@saleagent')->name('saleagent.notifications')->middleware('ajax');
    Route::get('saleagent-notification-read/{id}', 'NotificationController@saleagent_read')->middleware('ajax');
    Route::get('saleagent-notification-readall', 'NotificationController@saleagent_readall')->name('saleagent.readall')->middleware('ajax');

    Route::resource('check', 'CheckController');
    Route::get('get-usage', 'ConnectionController@get_usage');

    Route::prefix('searchAll')->group(function () {
//        Route::get('/{start?}/{end?}', 'SearchController@index')->name('search.usage');
        Route::get('/day/{start?}/{end?}', 'SearchController@search_day')->name('searchall.day');
        Route::get('/month/{start?}/{end?}', 'SearchController@search_month')->name('searchall.month');
        Route::get('/top_metrics/{start?}/{end?}', 'SearchController@search_top_metrics')->name('searchall.topmetrics');
        Route::get('/connections', 'SearchController@search_connections')->name('searchall.connections');
        Route::get('/default_dates', 'SearchController@default_dates')->name('searchall.dates');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getFullNameAttribute($value)
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    public function devices()
    {
        return $this->hasMany(Device::class);
    }

    public function connections()
    {
        return $this->hasMany(Connection::class);
    }

    public function wallet()
    {
        return $this->hasMany(Wallet::class, 'client_id');
    }

    public function company()
    {
        return $this->hasOne(Company::class, 'user_id');
    }

    public function client_quotes()
    {
        return $this->hasMany(Quote::class, 'client_id');
    }

    public function saleagent_quotes()
    {
        return $this->hasMany(Quote::class, 'user_id');
    }

    public function usage()
    {
        return $this->hasManyThrough(Usage::class, Connection::class);
    }
}

resources/views/admin/create.blade.php
@extends('layouts/app')

@section('content')

    <div class="container" style="margin-top: 10px;">
        <div class="bg-section">
            <h2>Create Admin</h2>
            <form method="post" action="{{ route('admin.store') }}">
                @csrf
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <input type="text" name="first_name" id="first_name" class="form-control"
                                   value="{{ old('first_name') }}"
                                   placeholder="First Name">
                            @if ($errors->has('first_name'))
                                <span class="invalid-feedback" role="alert">
                    <strong class="text-danger">{{ $errors->first('first_name') }}</strong>
                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <input type="text" name="last_name" id="last_name" class="form-control"
                                   placeholder="Last Name" value="{{ old('last_name') }}">
                            @if ($errors->has('last_name'))
                                <span class="invalid-feedback" role="alert">
                    <strong class="text-danger">{{ $errors->first('last_name') }}</strong>
                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <input type="text" name="email" id="email" class="form-control"
                                   value="{{ old('email') }}" placeholder="E-Mail">
                            @if ($errors->has('email'))
                                <span class="invalid-feedback" role="alert">
                    <strong class="text-danger">{{ $errors->first('email') }}</strong>
                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <input type="text" name="mobile" id="mobile" class="form-control"
                                   value="{{ old('mobile') }}" placeholder="Mobile Number">
                            @if ($errors->has('mobile'))
                                <span class="invalid-feedback" role="alert">
                    <strong class="text-danger">{{ $errors->first('mobile') }}</strong>
                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                            @if ($errors->has('password'))
                                <span class="invalid-feedback" role="alert">
                                    <strong class="text-danger">{{ $errors->first('password') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <input type="submit" class="btn btn-primary" value="Create Admin">
                    </div>

                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/edit.blade.php
@extends('layouts/app')

@section('content')

    <div class="container" style="margin-top: 10px;">
        <div class="bg-section">
            <h2>Edit Admin ({{ $user->fullName }})</h2>
            <form method="post" action="{{ route('admin.update', ['id' => $user->id]) }}">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <input type="text" value="{{ $user->first_name }}" name="first_name" id="first_name" class="form-control"
                                   placeholder="First Name">
                            @if ($errors->has('first_name'))
                                <span class="invalid-feedback" role="alert">
                    <strong class="text-danger">{{ $errors->first('first_name') }}</strong>
                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <input type="text" value="{{ $user->last_name }}" name="last_name" id="last_name" class="form-control"
                                   placeholder="Last Name" value="{{ old('last_name') }}">
                            @if ($errors->has('last_name'))
                                <span class="invalid-feedback" role="alert">
                    <strong class="text-danger">{{ $errors->first('last_name') }}</strong>
                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <input type="text" name="email" value="{{ $user->email }}" id="email" class="form-control"
                             placeholder="E-Mail">
                            @if ($errors->has('email'))
                                <span class="invalid-feedback" role="alert">
                    <strong class="text-danger">{{ $errors->first('email') }}</strong>
                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <input type="text" name="mobile" value="{{ $user->mobile }}" id="mobile" class="form-control"
                                 placeholder="Mobile Number">
                            @if ($errors->has('mobile'))
                                <span class="invalid-feedback" role="alert">
                    <strong class="text-danger">{{ $errors->first('mobile') }}</strong>
                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                            @if ($errors->has('password'))
                                <span class="invalid-feedback" role="alert">
                                    <strong class="text-danger">{{ $errors->first('password') }}</strong>
                                </span>
                            @else
                                <span class="invalid-feedback" role="alert">
                                    <small class="text-primary">Leave Password Blank if you don't want to update</small>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <input type="submit" class="btn btn-primary" value="Update Admin">
                    </div>

                </div>

            </form>
        </div>
    </div>

@endsection

@section('styles')

@endsection

@section('scripts')

@endsection

resources/views/admin/index.blade.php
@extends('layouts/app')

@section('content')
    <div class="container">
        <div class="bg-section">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            <div class="row">
                @role('superuser')
                <div class="col-sm-12 form-group text-right">
                    <a href="{{ route('admin.create') }}" class="btn btn-primary">Create Admin</a>
                </div>
                @endrole
                <div class="col-sm-12">
                    @if($users->isEmpty() == false)
                        <div class="table-responsive">
                            <table class="table dataTable">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $user->full_name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ $user->mobile }}</td>
                                        <td>
                                            <div class="dropdown">
                                                <a class="btn btn-link dropdown-toggle" type="button" id="nh_5_dd" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                    <i class="mdi mdi-more-horiz"></i>
                                                </a>
                                                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="nh_5_dd">
                                                    <li><a href="{{ route('admin.edit', ['id' => $user->id]) }}">Edit</a></li>
                                                    <li><a href="#" onclick="event.preventDefault();
                                                        document.getElementById('deleteForm{{ $user->id }}').submit();">Delete</a></li>
                                                    <form style="display: none" id="deleteForm{{ $user->id }}" action="{{ route('admin.destroy', ['id' => $user->id]) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                    </form>
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div class="alert alert-warning">
                            <strong>Not Found!</strong> You can add new users <a href="{{ route($url.'.create') }}">here</a>.
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

@section('styles')
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables/media/css/jquery.dataTables.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/icheck-bootstrap/icheck-bootstrap.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/switchery/dist/switchery.css') }}">
@endsection
@section('scripts')
    <script src="{{ asset('assets/plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/plugins/switchery/dist/switchery.js') }}"></script>
    <script src="{{ asset('assets/plugins/highcharts/js/highcharts.js') }}"></script>
@endsection