routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('test', 'JasperController@test');

Route::get('check', 'CheckController@index');
Route::get('send/email', 'MailController@sendemail');

Route::get('/register_view', 'Auth\RegisterController@register_view');
Auth::routes();
Auth::routes(['verify' => true]);

//For All Logged in Users
Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    Route::resource('settings', 'SettingController')->only(['index', 'store']);
    Route::resource('saleagent', 'SaleAgentController');
    Route::resource('admin', 'AdminController');
    Route::resource('client', 'ClientController');
    Route::get('edit-account', 'UserController@edit_account')->name('edit-account');
    Route::put('update-account', 'UserController@update_account')->name('update-account');
    Route::get('user/{id}/profile', 'UserController@show_profile')->name('profile.show');
    Route::get('accont/{id}', 'Homecontroller@account_detial')->name('account.show');
    Route::prefix('client')->group(function () {
        Route::get('get-usage/{id}', 'ClientController@get_usage');
    });


    Route::resource('devices', 'DeviceController');
    Route::resource('connections', 'ConnectionController');

    Route::prefix('connections')->group(function () {
        Route::get('{id}/add-deal-info', 'ConnectionController@deal_info')->name('connection.deal_info');
    });
    Route::get('device-connections/{slug}', 'DeviceController@connections')->name('device.connections');
    Route::put('add-connection/{id}', 'DeviceController@store_connection')->name('connection.store');
    Route::put('remove-connection/{id}', 'DeviceController@remove_connection')->name('connection.remove');


    Route::resource('packages', 'PackageController')->except(['show', 'destroy']);


//Admin only routes
    Route::group(['middleware' => ['role:admin|superuser', 'auth']], function () {
        Route::get('sync-devices', 'DeviceController@sync_devices')->name('sync');
        Route::get('sync-devices-ajax', 'DeviceController@sync_devices_ajax')->name('sync-ajax');

        Route::get('quote/{quote_id}/attach_connection', 'DealController@attach_connections')->name('attach.deal_conn');
        Route::post('quote/{quote_id}/attach_connection', 'DealController@store_attach_connections')->name('store.deal_conn');

        Route::get('bulk-deal-info/create', 'ConnectionController@deal_info_bulk')->name('deal_info_bulk');
        Route::get('ajax/client_deals/{client_id}', 'ConnectionController@client_deals');
        Route::put('add-bulk-deal-info', 'ConnectionController@store_deal_info_bulk')->name('store_deal_info');

        Route::get('admin-notifications', 'NotificationController@admin')->name('admin.notifications')->middleware('ajax');
        Route::get('admin-notification-read/{id}', 'NotificationController@admin_read')->middleware('ajax');
        Route::get('admin-notification-readall', 'NotificationController@admin_readall')->name('admin.readall')->middleware('ajax');
        Route::get('assign/sims', 'AssignSimController@create')->name('assign.sim.create');
        Route::post('assign/sims', 'AssignSimController@store')->name('assign.sim.store');
        Route::get('assign/sims/{id}/edit', 'AssignSimController@edit')->name('assign.sim.edit');
        Route::post('assign/sims/{id}/update', 'AssignSimController@update')->name('assign.sim.update');
        Route::get('assign/list', 'AssignSimController@index')->name('assign.sim.index');
        Route::get('deassign/{id}/sim', 'AssignSimController@deassign')->name('deassign.sim');
    });



    Route::get('connection-dayssearch/{iccid}/{start}/{end}', 'ConnectionController@days_search')->name('connection.daysearch');
    Route::get('connection-monthsearch/{iccid}/{start}/{end}', 'ConnectionController@month_search')->name('connection.monthsearch');


    Route::resource('quote', 'QuoteController');
    Route::prefix('quote/{quote_id}')->group(function () {
        Route::resource('deal', 'DealController');
        Route::get('/deal/individual/create', 'DealController@create')->name('deal.individual');

        Route::prefix('/deal/pooled')->group(function () {
            Route::get('/create', 'DealController@pooled')->name('deal.pooled');
            Route::post('/store', 'DealController@store_pooled')->name('store.pooled');
        });

        Route::get('send', 'QuoteController@send')->name('quote.send');
        Route::put('save', 'QuoteController@save_paymentplan')->name('save.paymentplan');
        Route::get('approve/', 'QuoteController@approve')->name('quote.approve');
    });
    Route::get('get-quote-price/{deal_type}/{product_type_id}/{data_usage}', 'QuoteController@get_quote_price');
    Route::get('get-volume/{deal_type}/{volume_id}', 'QuoteController@get_volume');
    Route::get('get-data-volume/{deal_type}/{type}', 'QuoteController@get_datavolume');

    Route::resource('wallet', 'WalletController')->except(['show', 'delete']);

    //Notifications
    Route::get('saleagent-notifications', 'NotificationController@saleagent')->name('saleagent.notifications')->middleware('ajax');
    Route::get('saleagent-notification-read/{id}', 'NotificationController@saleagent_read')->middleware('ajax');
    Route::get('saleagent-notification-readall', 'NotificationController@saleagent_readall')->name('saleagent.readall')->middleware('ajax');

    Route::resource('check', 'CheckController');
    Route::get('get-usage', 'ConnectionController@get_usage');

    Route::prefix('searchAll')->group(function () {
//        Route::get('/{start?}/{end?}', 'SearchController@index')->name('search.usage');
        Route::get('/day/{start?}/{end?}', 'SearchController@search_day')->name('searchall.day');
        Route::get('/month/{start?}/{end?}', 'SearchController@search_month')->name('searchall.month');
        Route::get('/top_metrics/{start?}/{end?}', 'SearchController@search_top_metrics')->name('searchall.topmetrics');
        Route::get('/connections', 'SearchController@search_connections')->name('searchall.connections');
        Route::get('/default_dates', 'SearchController@default_dates')->name('searchall.dates');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getFullNameAttribute($value)
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    public function devices()
    {
        return $this->hasMany(Device::class);
    }

    public function connections()
    {
        return $this->hasMany(Connection::class);
    }

    public function wallet()
    {
        return $this->hasMany(Wallet::class, 'client_id');
    }

    public function company()
    {
        return $this->hasOne(Company::class, 'user_id');
    }

    public function client_quotes()
    {
        return $this->hasMany(Quote::class, 'client_id');
    }

    public function saleagent_quotes()
    {
        return $this->hasMany(Quote::class, 'user_id');
    }

    public function usage()
    {
        return $this->hasManyThrough(Usage::class, Connection::class);
    }
}

resources/views/quote-old/email.blade.php
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h3>Client: {{ ucwords($quote->client->full_name) }}</h3>
            </div>
            <div class="col-sm-6">
                <h3>Order Number: {{ ucwords($quote->order_number) }}</h3>
            </div>
        </div>

        <div class="row">
            @php
                $installs = new \Illuminate\Support\Collection();
                if($quote->deals){
                foreach($quote->deals as $deal){
                    if($deal->payment_terms == 'monthly'){
                        $con = $deal->contract_len - 3;
                        $ins = $deal->installment;

                        for($i=1; $i<=$con; $i++){
                            $arr = [
                                'month' => 'Month '.$i,
                                'install' => $ins,
                            ];
                            $installs->push($arr);
                        }
                    }
                }
                }
                $months = $installs->groupBy(function ($r){
                    return $r['month'];
                })->map(function ($group){
                    return $group->sum('install');
                });
            @endphp
            @foreach($months as $mon => $ins)
                <div class="col-sm-1 col-xs-6 form-group"><strong>{{ $mon }}:</strong> ${{ $ins }}</div>
            @endforeach
        </div>

        @foreach($quote->deals as $deal)
            <div class="row form-group">
                <div class="col-sm-12">
                    <div class="table-responsive">
                        <table class="table table-bordered no-footer">
                            <thead>
                            <tr>
                                <th colspan="2" class="col-xs-6"><h4>Deal {{ $loop->iteration }}</h4></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Product Type</td>
                                <td>{{ $deal->product_type->name }}</td>
                            </tr>
                            <tr>
                                <td>Data Type</td>
                                <td>{{ $deal->data_type }}</td>
                            </tr>
                            <tr>
                                <td>Data Usage</td>
                                <td>{{ $deal->data }}</td>
                            </tr>
                            <tr>
                                @php
                                    $networks = \App\Models\Network::get();
                                    $exploded = explode(',', $deal->network_preferences);
                                    $nets = [];
                                    foreach($exploded as $id){
                                        $nets[] = $networks->where('id', $id)->first()->name;
                                    }
                                    $nets = implode(',', $nets);
                                @endphp
                                <td>Network Preferences</td>
                                <td>{{ $nets }}</td>
                            </tr>
                            <tr>
                                <td>Sim Volumn</td>
                                <td>{{ $deal->sim_volumn }}</td>
                            </tr>
                            <tr>
                                <td>Data Volumn</td>
                                <td>{{ $deal->volumn->name }}</td>
                            </tr>
                            <tr>
                                <td>Contract Length</td>
                                <td>{{ $deal->contract_len.' Month' }}</td>
                            </tr>
                            <tr>
                                <td>Client Application</td>
                                <td>{{ $deal->client_application->name }}</td>
                            </tr>
                            <tr>
                                <td>Basic Price</td>
                                <td>${{ $deal->base_price }}</td>
                            </tr>
                            <tr>
                                <td>Margin Price</td>
                                <td>${{ $deal->margin_sales }}</td>
                            </tr>
                            <tr>
                                <td>Client Rate</td>
                                <td>${{ $deal->client_price }}</td>
                            </tr>
                            <tr>
                                <td>Total Deal Value</td>
                                <td>${{ $deal->total_deal }}</td>
                            </tr>
                            <tr>
                                <td>Total Comission</td>
                                <td>${{ $deal->total_commission }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
</section>

resources/views/quote-old/index.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables/media/css/jquery.dataTables.css') }}">
@endsection
@section('scripts')
    <script src="{{ asset('assets/plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
@endsection

@section('content')

    <section class="bg-section form-group">
        <div class="container">

            <div class="row overallStats">
                <div class="col-sm-3 col-xs-6">
                    <div class="stat">

                        <div class="stat-value">{{ $quotes->count() }}</div>
                        <div class="stat-label">Total Quotes</div>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <div class="stat">
                        <div class="stat-value">{{ $quotes->where('status', 'Draft')->count() }}</div>
                        <div class="stat-label">Draft</div>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <div class="stat">
                        <div class="stat-value">{{ $quotes->where('status', 'Sent')->count() }}</div>
                        <div class="stat-label">Sent</div>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <div class="stat">
                        <div class="stat-value">{{ $quotes->where('status', 'Approved')->count() }}</div>
                        <div class="stat-label">Approved</div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="table-responsive">
                        <table class="table table-bordered dataTable no-footer">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Client</th>
                                <th>Order Number</th>
                                <th>Status</th>
                                @hasrole('admin')
                                <th>Added By</th>
                                @endhasrole
                                <th>Added On</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($quotes as $quote)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td><a href="">{{ $quote->client->full_name }}</a></td>
                                    <td>{{ $quote->order_number }}</td>
                                    <td>{{ $quote->status }}</td>
                                    @hasrole('admin')
                                    <td>{{ $quote->user->full_name }}</td>
                                    @endhasrole
                                    <td>{{ $quote->created_at->format('d M, Y') }}</td>
                                    <td class="text-center">
                                        <ul class="list-inline">
                                            @hasanyrole('admin|saleagent')
                                            <li>
                                                <a href="{{ route('deal.create', $quote)  }}" data-toggle="tooltip"
                                                   title="Add New Deal"><i class="fa fa-plus-square"></i></a>
                                            </li>
                                            @endhasanyrole
                                            <li>
                                                <a href="{{ route('quote.show',$quote) }}" data-toggle="tooltip"
                                                   title="View Quote"><i class="fa fa-search"></i></a>
                                            </li>
                                            @hasanyrole('admin|saleagent')
                                            <li>
                                                <a href="{{ route('quote.send', $quote->id)  }}" data-toggle="tooltip"
                                                   title="Send Quote in Email"><i class="fa fa-location-arrow"></i></a>
                                            </li>
                                            @endhasanyrole
                                            @if($quote->status == 'Sent' && Auth::user()->hasRole('admin'))
                                                <li>
                                                    <a href="{{ route('quote.approve', $quote->id)  }}"
                                                       data-toggle="tooltip"
                                                       title="Approve Quote"><i class="fa fa-check-circle"></i></a>
                                                </li>
                                            @endif

                                            @if($quote->status == 'Approved')
                                                <li>
                                                    <a href="{{ route('attach.deal_conn', $quote->id) }}" data-toggle="tooltip" title="Add Connections">
                                                        <i class="fa fa-plus"></i>
                                                    </a>
                                                </li>
                                            @endif
                                        </ul>

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/quote-old/show.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables/media/css/jquery.dataTables.css') }}">
@endsection
@section('scripts')
    <script src="{{ asset('assets/plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
@endsection

@section('content')
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h3>Client: {{ ucwords($quote->client->full_name) }}</h3>
                </div>
                <div class="col-sm-6">
                    <h3>Order Number: {{ ucwords($quote->order_number) }}</h3>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12 form-group">Total Upfront: <strong>${{ $quote->deals->sum('advance_payment') }}</strong>
                </div>
                @if(!$quote->installments->isEmpty())
                    @php
                        $monthly = $quote->installments->groupBy(function ($q){
                            return $q->date->format('m-Y');
                        })->map(function ($row) {
                            return (string) $row->sum('amount');
                        });
                        $array = $monthly->toArray();
                        $unique = array_count_values($array);
                        $total = $monthly->sum();
                    @endphp
                    @foreach($unique as $amount => $months)
                        <div class="col-sm-12">{{ $months }}x Monthly Installments: <strong>${{ $amount }}</strong></div>
                    @endforeach
                    @foreach($monthly as $month => $sum)
                        <div class="col-sm-1 col-xs-6 form-group"><strong>{{ 'Month '.$loop->iteration }}</strong> ${{ $sum }}</div>
                    @endforeach
                @else
                    @php
                        $installs = new \Illuminate\Support\Collection();
                        if($quote->deals){
                        foreach($quote->deals as $deal){
                            if($deal->payment_terms == 'monthly'){
                                $con = $deal->contract_len - 3;
                                $ins = $deal->installment;

                                for($i=1; $i<=$con; $i++){
                                    $arr = [
                                        'month' => 'Month '.$i,
                                        'install' => $ins,
                                    ];
                                    $installs->push($arr);
                                }
                            }
                        }
                        }
                        $months = $installs->groupBy(function ($r){
                            return $r['month'];
                        })->map(function ($group){
                            return $group->sum('install');
                        });
                    @endphp
                    @foreach($months as $mon => $ins)
                        <div class="col-sm-1 col-xs-6 form-group"><strong>{{ $mon }}:</strong> ${{ $ins }}</div>
                    @endforeach
                @endif
            </div>

            <div class="row">
                @foreach($quote->deals as $deal)
                    <div class="col-sm-4 form-group">
                        <div class="table-responsive bg-section" style="padding: 0">
                            <table class="table table-bordered no-footer">
                                <thead>
                                <tr>
                                    <th colspan="2"><h4>Deal {{ $loop->iteration }}</h4></th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td class="col-xs-6">Product Type</td>
                                    <td class="col-xs-6">{{ $deal->product_type->name }}</td>
                                </tr>
                                <tr>
                                    <td>Data Type</td>
                                    <td>{{ $deal->data_type }}</td>
                                </tr>
                                <tr>
                                    <td>Data Usage</td>
                                    <td>{{ $deal->data }}</td>
                                </tr>
                                <tr>
                                    @php
                                        $networks = \App\Models\Network::get();
                                        $exploded = explode(',', $deal->network_preferences);
                                        $nets = [];
                                        foreach($exploded as $id){
                                            $nets[] = $networks->where('id', $id)->first()->name;
                                        }
                                        $nets = implode(',', $nets);
                                    @endphp
                                    <td>Network Preferences</td>
                                    <td>{{ $nets }}</td>
                                </tr>
                                <tr>
                                    <td>Sim Volumn</td>
                                    <td>{{ $deal->sim_volumn }}</td>
                                </tr>
                                <tr>
                                    <td>Data Volumn</td>
                                    <td>{{ $deal->volumn->name }}</td>
                                </tr>
                                <tr>
                                    <td>Contract Length</td>
                                    <td>{{ $deal->contract_len.' Month' }}</td>
                                </tr>
                                <tr>
                                    <td>Client Application</td>
                                    <td>{{ $deal->client_application->name }}</td>
                                </tr>
                                <tr>
                                    <td>Basic Price</td>
                                    <td>${{ $deal->base_price }}</td>
                                </tr>
                                <tr>
                                    <td>Margin Price</td>
                                    <td>${{ $deal->margin_sales }}</td>
                                </tr>
                                <tr>
                                    <td>Client Rate</td>
                                    <td>${{ $deal->client_price }}</td>
                                </tr>
                                <tr>
                                    <td>Total Deal Value</td>
                                    <td>${{ $deal->total_deal }}</td>
                                </tr>
                                <tr>
                                    <td>Total Comission</td>
                                    <td>${{ $deal->total_commission }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                @endforeach
            </div>
            <a href="{{ url('quote/send', $quote->id)  }}" class="btn btn-primary">Send</a>
        </div>
    </section>
@endsection