routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('test', 'JasperController@test');

Route::get('check', 'CheckController@index');
Route::get('send/email', 'MailController@sendemail');

Route::get('/register_view', 'Auth\RegisterController@register_view');
Auth::routes();
Auth::routes(['verify' => true]);

//For All Logged in Users
Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    Route::resource('settings', 'SettingController')->only(['index', 'store']);
    Route::resource('saleagent', 'SaleAgentController');
    Route::resource('admin', 'AdminController');
    Route::resource('client', 'ClientController');
    Route::get('edit-account', 'UserController@edit_account')->name('edit-account');
    Route::put('update-account', 'UserController@update_account')->name('update-account');
    Route::get('user/{id}/profile', 'UserController@show_profile')->name('profile.show');
    Route::get('accont/{id}', 'Homecontroller@account_detial')->name('account.show');
    Route::prefix('client')->group(function () {
        Route::get('get-usage/{id}', 'ClientController@get_usage');
    });


    Route::resource('devices', 'DeviceController');
    Route::resource('connections', 'ConnectionController');

    Route::prefix('connections')->group(function () {
        Route::get('{id}/add-deal-info', 'ConnectionController@deal_info')->name('connection.deal_info');
    });
    Route::get('device-connections/{slug}', 'DeviceController@connections')->name('device.connections');
    Route::put('add-connection/{id}', 'DeviceController@store_connection')->name('connection.store');
    Route::put('remove-connection/{id}', 'DeviceController@remove_connection')->name('connection.remove');


    Route::resource('packages', 'PackageController')->except(['show', 'destroy']);


//Admin only routes
    Route::group(['middleware' => ['role:admin|superuser', 'auth']], function () {
        Route::get('sync-devices', 'DeviceController@sync_devices')->name('sync');
        Route::get('sync-devices-ajax', 'DeviceController@sync_devices_ajax')->name('sync-ajax');

        Route::get('quote/{quote_id}/attach_connection', 'DealController@attach_connections')->name('attach.deal_conn');
        Route::post('quote/{quote_id}/attach_connection', 'DealController@store_attach_connections')->name('store.deal_conn');

        Route::get('bulk-deal-info/create', 'ConnectionController@deal_info_bulk')->name('deal_info_bulk');
        Route::get('ajax/client_deals/{client_id}', 'ConnectionController@client_deals');
        Route::put('add-bulk-deal-info', 'ConnectionController@store_deal_info_bulk')->name('store_deal_info');

        Route::get('admin-notifications', 'NotificationController@admin')->name('admin.notifications')->middleware('ajax');
        Route::get('admin-notification-read/{id}', 'NotificationController@admin_read')->middleware('ajax');
        Route::get('admin-notification-readall', 'NotificationController@admin_readall')->name('admin.readall')->middleware('ajax');
        Route::get('assign/sims', 'AssignSimController@create')->name('assign.sim.create');
        Route::post('assign/sims', 'AssignSimController@store')->name('assign.sim.store');
        Route::get('assign/sims/{id}/edit', 'AssignSimController@edit')->name('assign.sim.edit');
        Route::post('assign/sims/{id}/update', 'AssignSimController@update')->name('assign.sim.update');
        Route::get('assign/list', 'AssignSimController@index')->name('assign.sim.index');
        Route::get('deassign/{id}/sim', 'AssignSimController@deassign')->name('deassign.sim');
    });



    Route::get('connection-dayssearch/{iccid}/{start}/{end}', 'ConnectionController@days_search')->name('connection.daysearch');
    Route::get('connection-monthsearch/{iccid}/{start}/{end}', 'ConnectionController@month_search')->name('connection.monthsearch');


    Route::resource('quote', 'QuoteController');
    Route::prefix('quote/{quote_id}')->group(function () {
        Route::resource('deal', 'DealController');
        Route::get('/deal/individual/create', 'DealController@create')->name('deal.individual');

        Route::prefix('/deal/pooled')->group(function () {
            Route::get('/create', 'DealController@pooled')->name('deal.pooled');
            Route::post('/store', 'DealController@store_pooled')->name('store.pooled');
        });

        Route::get('send', 'QuoteController@send')->name('quote.send');
        Route::put('save', 'QuoteController@save_paymentplan')->name('save.paymentplan');
        Route::get('approve/', 'QuoteController@approve')->name('quote.approve');
    });
    Route::get('get-quote-price/{deal_type}/{product_type_id}/{data_usage}', 'QuoteController@get_quote_price');
    Route::get('get-volume/{deal_type}/{volume_id}', 'QuoteController@get_volume');
    Route::get('get-data-volume/{deal_type}/{type}', 'QuoteController@get_datavolume');

    Route::resource('wallet', 'WalletController')->except(['show', 'delete']);

    //Notifications
    Route::get('saleagent-notifications', 'NotificationController@saleagent')->name('saleagent.notifications')->middleware('ajax');
    Route::get('saleagent-notification-read/{id}', 'NotificationController@saleagent_read')->middleware('ajax');
    Route::get('saleagent-notification-readall', 'NotificationController@saleagent_readall')->name('saleagent.readall')->middleware('ajax');

    Route::resource('check', 'CheckController');
    Route::get('get-usage', 'ConnectionController@get_usage');

    Route::prefix('searchAll')->group(function () {
//        Route::get('/{start?}/{end?}', 'SearchController@index')->name('search.usage');
        Route::get('/day/{start?}/{end?}', 'SearchController@search_day')->name('searchall.day');
        Route::get('/month/{start?}/{end?}', 'SearchController@search_month')->name('searchall.month');
        Route::get('/top_metrics/{start?}/{end?}', 'SearchController@search_top_metrics')->name('searchall.topmetrics');
        Route::get('/connections', 'SearchController@search_connections')->name('searchall.connections');
        Route::get('/default_dates', 'SearchController@default_dates')->name('searchall.dates');
    });
});

app/Models/Wallet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Wallet extends Model
{
    protected $guarded = [];

    public function client()
    {
        return $this->belongsTo(User::class, 'client_id');
    }

    public function added_by()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/WalletController.php
<?php

namespace App\Http\Controllers;

use App\Models\Wallet;
use App\Http\Requests\StoreWalletAmount;
use Illuminate\Support\Facades\Auth;
use App\Models\User;

class WalletController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin|client');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('wallet.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $wallet = new Wallet;
        $clients = User::role('client')->get();
        return view('wallet.create', compact('wallet', 'clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreWalletAmount $request)
    {
        $data = $request->except(['_token', 'client']);
        $data['client_id'] = $request->client;
        $data['user_id'] = Auth::user()->id;

        $wl = new Wallet($data);
        $wl->save();
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Wallet  $wallet
     * @return \Illuminate\Http\Response
     */
    public function show(Wallet $wallet)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Wallet  $wallet
     * @return \Illuminate\Http\Response
     */
    public function edit(Wallet $wallet)
    {
        $wallet = Wallet::findOrFail($wallet)->first();
        $clients = User::role('client')->get();
        return view('wallet.edit', compact('wallet', 'clients'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Wallet  $wallet
     * @return \Illuminate\Http\Response
     */
    public function update(StoreWalletAmount $request, Wallet $wallet)
    {
        $data = $request->except('_token', '_method', 'client');
        $data['client_id'] = $request->client;

        $wallet->update($data);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Wallet  $wallet
     * @return \Illuminate\Http\Response
     */
    public function destroy(Wallet $wallet)
    {
        //
    }
}

resources/views/wallet/_form.blade.php
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <label for="client">Client *</label>
            {!! Form::select('client', $clients->pluck('full_name', 'id')->prepend(' -- Select Client -- ', ''), old('client', $wallet->client_id), ['id'=> 'client', 'class'=>'form-control select2']) !!}

            @if ($errors->has('client'))
                <span class="invalid-feedback" role="alert">
                    <strong class="text-danger">{{ $errors->first('client') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="col-sm-6">
        <div class="form-group">
            <label for="amount">Amount *</label>
            <input type="number" name="amount" id="amount" class="form-control"
                   value="{{ old('amount', $wallet->amount) }}">

            @if ($errors->has('amount'))
                <span class="invalid-feedback" role="alert">
                    <strong class="text-danger">{{ $errors->first('amount') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="col-sm-12">
        <input type="submit" class="btn btn-primary" value="{{ $wallet->id ? 'Update' : 'Save' }}">
    </div>
</div>

resources/views/wallet/create.blade.php
@extends('layouts.app')

@section('styles')
@endsection
@section('scripts')
@endsection

@section('content')
    <section class="section">
        <div class="container">

            <form action="{{ route('wallet.store') }}" method="POST" role="form">
                @csrf

                @include('wallet._form')

            </form>

        </div>
    </section>
@endsection

resources/views/wallet/edit.blade.php
@extends('layouts.app')

@section('styles')
@endsection
@section('scripts')
@endsection

@section('content')
    <section class="section">
        <div class="container">

            <form action="{{ route('wallet.update', $wallet) }}" method="POST" role="form">
                @method('put')
                @csrf

                @include('wallet._form')

            </form>

        </div>
    </section>
@endsection

resources/views/wallet/index.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables/media/css/jquery.dataTables.css') }}">
@endsection
@section('scripts')
    <script src="{{ asset('assets/plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
@endsection

@section('content')
    <section class="section">
        <div class="container">
            @role('client')
            @php
                $user = \Illuminate\Support\Facades\Auth::user();
                $wallet = \App\Models\Wallet::with('client')
                ->where('client_id', $user->id)
                ->get();
            @endphp
            @if(!$wallet->isEmpty())
                <div class="row">
                    <div class="col-sm-12 text-right">
                        <h3>Total Amount: ${{ round($wallet->sum('amount'), 2) }}</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive">
                            <table class="table table-bordered dataTable no-footer">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Amount</th>
                                    <th>Transaction Date</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($wallet as $wal)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $wal->amount }}</td>
                                        <td>{{ $wal->created_at->format('d M, Y') }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            @else
                <div class="alert alert-danger">
                    <strong>No Amount Found!</strong>
                </div>
            @endif
            @endrole


            @role('admin')
            @php
                $clients = \App\Models\User::role('client')->with('wallet')->get();
            @endphp
            @if(!$clients->isEmpty())
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive">
                            <table class="table table-bordered dataTable no-footer">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Client</th>
                                    <th>Amount</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($clients as $client)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td><a href="">{{ $client->full_name }}</a></td>
                                        <td>{{ $client->wallet->sum('amount') }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            @else
                <div class="alert alert-danger">
                    <strong>No Amount Found!</strong>
                </div>
            @endif
            @endrole
        </div>
    </section>
@endsection